### ISSUE TITLE
jsPanel positioning is off in Mozilla Firefox 32

### ISSUE THREAD

**Issue by temuri416** [Flyer53/jsPanel3#17] opened 2016-09-23 15:22 UTC
Hi,
1. Open http://jspanel.de/api/ in Mozilla Firefox 32.
2. Execute first example.
3. No panel is displayed.
4. Execute second example.
5. Panel is displayed, but is positioned incorrectly.

IMO v32 is not that ancient, maybe you could take a look :-)

Thanks!

**Comment by Flyer53** [comment] 2016-09-23 17:14
Ok, the behaviour is confirmed.
Both panels are there, but the css top and left values are not assigned to the panels. 

Don't know why yet, but I'll try to find out.

However, for what reason would you want to use Firefox version 32? Current is 49!

**Comment by temuri416** [comment] 2016-09-23 17:22
Thanks, Stefan.

The reason I am using v32 is that it is one of the last releases that does not require Firebug v2.x, which I cannot stand - its debugger is too slow.

I'll appreciate fixing it, for now I have to stick with Chrome's dev tools, which I don't like too much :-)

**Comment by Flyer53** [comment] 2016-09-23 18:06
Ok. In case positioning is not the crucial part right now I suggest the following workaround:

``` javascript
$.jsPanel({
  // config
}).css({left: 100, top: 100});

// or:
$.jsPanel({
  // config
  callback: function() {
    this.css({left: 100, top: 100});
  }
});
```

That at least moves the panel in sight.

Btw: I'm working on v3.4 which will accept the value **"none"** for option.theme resulting in a panel that is all white and doesn't have any theme related classes/styles applied. Further I'll add support for Material Design for Bootstrap themes, so can do something like _theme: "mdb-secondary"_ for example.

**Comment by temuri416** [comment] 2016-09-23 18:16
I understand it's a low-priority. But I'll have to figure out a workaround, as I rely on precise positioning having multiple panels on the page. Stacking them all at 100x100 position will not work for me.
1. Can you outline the problem for me or point at the code that's responsible for the problem?
2. Will you fix it eventually, or is it categorized as "won't fix"?

Thanks!

**Comment by Flyer53** [comment] 2016-09-23 18:30
Well, I'll try to find the bug.
It happened somewhere in the version 3.2.0 release I found out so far.
Another workaround for the time being would be to go back to version 3.1.1 which doesn't show this bug.

**Comment by temuri416** [comment] 2016-09-23 18:32
Thanks, that helps. I'll temporarily go back to 3.1.1 then.

**Comment by Flyer53** [comment] 2016-09-23 19:05
Found it ....
As of version 3.2.0 I replaced a function (inside the positioning engine) to get a computed style with _window.getComputedStyle()_. Obviously FF v32 can't handle that.
I prepared a jsPanel 3.4.0 alpha to work with FF v32. You can download it from
http://jspanel.de/downloads/jspanel-3.4.0-alpha-temuri.zip
Don't know yet whether I reverse this change permanently ...

**Comment by temuri416** [comment] 2016-09-23 19:09
Maybe you should keep both and fall back when _window.getComputedStyle()_ does not exist?

**Comment by temuri416** [comment] 2016-09-23 19:12
According to http://caniuse.com/#feat=getcomputedstyle you need at least FF v47, which is quite recent.

**Comment by Flyer53** [comment] 2016-09-23 19:51
It's a little bit more complicated. _window.getComputedStyle()_ is in FF v32 but doesn't always return useful values.
Example:
Call **window.getComputedStyle(document.getElementById('page-banner'))['border-left-width'];**
on the api page. FF v32 returns **undefined** while a current FF returns **"0px"**

**Comment by Flyer53** [comment] 2016-10-28 15:45
Since this is not an issue with the current version of Firefox (at time of writing 49) topic is closed.

**Closed as completed by Flyer53** 2016-10-28 15:45 UTC
